# Generated by Django 5.1.1 on 2024-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('imc', models.FloatField()),
                ('hipertension', models.BooleanField()),
                ('cardiaca', models.BooleanField()),
                ('hba1c', models.FloatField()),
                ('glucosa', models.FloatField()),
                ('tabaquismo', models.CharField(choices=[('No fuma', 'No fuma'), ('Ex-fumador', 'Ex-fumador'), ('Fumador ocasional', 'Fumador ocasional'), ('Fumador habitual', 'Fumador habitual')], max_length=50)),
            ],
        ),
    ]
