# Generated by Django 5.1.1 on 2024-10-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
    ]
