# Generated by Django 5.1.1 on 2024-10-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodel', '0002_administracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cardiaca',
            new_name='enfermedad_cardiaca',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='glucosa',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hba1c',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='tabaquismo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='bmi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='historial_tabaquismo',
            field=models.IntegerField(choices=[(0, 'Nunca'), (1, 'Ex-fumador'), (2, 'Fumador ocasional'), (3, 'Fumador habitual')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel_glucosa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel_hba1c',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Hombre'), (0, 'Mujer'), (2, 'Otro')]),
        ),
    ]
